### ISSUE TITLE
cannot install trepan on python3.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rocky/python3-trepan#1]
```
What steps will reproduce the problem?
1. pip install trepan
2.
3.

What is the expected output? What do you see instead?
successful install.
Downloading/unpacking trepan
  Could not fetch URL http://code.google.com/p/trepan/ (from https://pypi.python.org/simple/trepan/): HTTP Error 404: Not Found
  Will skip URL http://code.google.com/p/trepan/ when looking for download links for trepan
  Using version 0.2.8 (newest of versions: 0.2.8, 0.2.8, 0.2.7, 0.2.5)
  Downloading trepan-0.2.8.tar.gz (130kB): 
  Downloading from URL https://pypi.python.org/packages/source/t/trepan/trepan-0.2.8.tar.gz#md5=216a9ee0e60df183a4c90e412d0cbf37 (from https://pypi.python.org/simple/trepan/)
...Downloading trepan-0.2.8.tar.gz (130kB): 130kB downloaded
  Running setup.py egg_info for package trepan
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_root/trepan/setup.py", line 12, in <module>
        from __pkginfo__ import \
    ImportError: No module named '__pkginfo__'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_root/trepan/setup.py", line 12, in <module>

    from __pkginfo__ import \

ImportError: No module named '__pkginfo__'

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in 
/tmp/pip_build_root/trepan
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/usr/lib/python3.3/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3.3/site-packages/pip/req.py", line 1134, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3.3/site-packages/pip/req.py", line 259, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3.3/site-packages/pip/util.py", line 670, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with 
error code 1 in /tmp/pip_build_root/trepan

Storing complete log in /root/.pip/pip.log

What version of the product are you using? On what operating system?
linux fedora 20

Please provide any additional information below.


```

Original issue reported on code.google.com by `finjulh...@gmail.com` on 18 Jul 2014 at 12:56

**Comment by rocky** [comment]
I think this is fixed now.
