### ISSUE TITLE
start_opts={'startup-profile': True}

### ISSUE THREAD

**Issue by yssource** [rocky/python3-trepan#15]
``` python
import trepan.api; trepan.api.debug(start_opts={'startup-profile': True})

# /tmp/p.py
``` python
print('xxxxxxxxxxx')
import trepan.api; trepan.api.debug(start_opts={'startup-profile': True})
print('xxxxxxxxxxx')
```

# Traceback
``` python
Traceback (most recent call last):
  File "/tmp/p.py", line 9, in <module>
    import trepan.api; trepan.api.debug(start_opts={'startup-profile': True})
  File "/home/xxx/workspace/python3-trepan/trepan/api.py", line 209, in debug
    options.add_startup_file(dbg_initfiles)
  File "/home/xxx/workspace/python3-trepan/trepan/options.py", line 49, in add_startup_file
    dbg_initfiles.append(startup_trepan_file)
AttributeError: 'bool' object has no attribute 'append'
trepan3k: That's all, folks...
```

**Comment by rocky** [comment]
The documentation you must have been following was incorrect. I have just corrected it at: 

https://python3-trepan.readthedocs.io/en/latest/entry-exit.html#calling-the-debugger-from-your-program

That option doesn't take a boolean argument as I had previously had and that you used above. Instead it takes a list of file names that should get run as startup profiles. See the example in the above link.

**Comment by yssource** [comment]
Thanks a lot.

`import trepan.api; trepan.api.debug(start_opts={'startup-profile': ['/home/User/.config/trepanpy/profile']})`

works for me.

**Comment by yssource** [comment]
It's possible to make `/home/User/.config/trepanpy/profile` as default startup-profile. 
Since, I wanna using `import trepan.api; trepan.api.debug()`, 
instead of `import trepan.api; trepan.api.debug(start_opts={'startup-profile': ['/home/User/.config/trepanpy/profile']})`

**Comment by rocky** [comment]
Right now there isn't a default profile doesn't get called when the debugger is called this way. It is possible to do, I suppose, but I don't think I'll undertake doing this. If you or others want to see add code to do this, by all means go ahead.

Note that there is a little bit of subtlety here. Even though I often put the import and the debug call together in one line to make it easy to add and remove, the import is in effect done once (and the remaining times nothing is done since importing an already imported module has no effect). 

The call to debug causes a halt. Presumably you don't want to run a startup profile _every_ time the debugger stops, just the _first_ time it stops.
