### ISSUE TITLE
Error building python3k-trepan

### ISSUE THREAD

**Issue by rmsilva1973** [rocky/python3-trepan#26]
Hi,

   I've cloned the repo and tried building it with

**python setup.py build**

(seemed to work)

then I tried:

**python setup.py install**

and it fails with the following error:

_Installed /home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/trepan3k-0.8.11-py3.8.egg
Processing dependencies for trepan3k==0.8.11
Searching for tracer>=0.3.2
Reading https://pypi.org/simple/tracer/
Downloading https://files.pythonhosted.org/packages/41/7c/73012494a7aa0d2e693ef0dc29304ea7968ac86a034ce8c0b0acd83640e3/tracer-0.3.2.tar.gz#sha256=1ddb3f438ea5ab4180776e8bb8bfa857edf7f52264f6b8189bba2bafb1a7cae3
Best match: tracer 0.3.2
Processing tracer-0.3.2.tar.gz
Writing /tmp/easy_install-orrau7k9/tracer-0.3.2/setup.cfg
Running tracer-0.3.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-orrau7k9/tracer-0.3.2/egg-dist-tmp-h9jpyk0z
Traceback (most recent call last):
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-orrau7k9/tracer-0.3.2/setup.py", line 8, in <module>
    if ((2, 4) <= SYS_VERSION <= (2, 7)):
ImportError: cannot import name 'package_dir' from '__pkginfo__' (/home/moutinho/projetos/python3-trepan/__pkginfo__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    setup(
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 425, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 721, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 765, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 781, in resolve
    dist = best[req.key] = env.best_match(
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 693, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 719, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 904, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1172, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in run_setup
    run_setup(setup_script, args)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/moutinho/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-orrau7k9/tracer-0.3.2/setup.py", line 8, in <module>
    if ((2, 4) <= SYS_VERSION <= (2, 7)):
ImportError: cannot import name 'package_dir' from '__pkginfo__' (/home/moutinho/projetos/python3-trepan/__pkginfo__.py)_

As you might notice, I was trying to install python3-trepan to debug an issue in pandas. That's why I'm inside pandas-dev environment on miniconda.

**Comment by rocky** [comment]
Make sure the python you are running in `python setup.py install` is Python 3.

**Comment by rmsilva1973** [comment]
@rocky It is:

 (pandas-dev) moutinho@LUNA:~/projetos/python3-trepan$ python --version
Python 3.8.2

**Comment by rocky** [comment]
Looks like the problem is in installing [tracer](https://pypi.org/project/tracer/). 

And it looks like the packaging for that is a bit old - it hasn't been changed in 7 years.


Can you install this by itself?

**Comment by rmsilva1973** [comment]
Installing tracer with pip allowed the installation to procceed, but it stopped a bit farther down with:

_error: xdis 4.5.0 is installed but xdis<4.5.0,>=4.4.0 is required by {'uncompyle6'}_

**Comment by rocky** [comment]
Install uncompyle6 from git right now untill there's another release of that.

There is a lot of upheaval right now in the decompilation part which is necessary to to be able to support more modern Pythons, and alas that is a strong dependency on trepan3k.

**Comment by rocky** [comment]
I've just released version 3.6.7 (and a new version of uncompyle6) whch should get everything back in sync. I think this will address this problem.
